---
apiVersion: v1
kind: Namespace
metadata:
  name: e2e-system
  labels:
    team: platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: e2e
  labels:
    team: platform
rules:
- apiGroups: [""]
  verbs: ["*"]
  resources:
    - "pods"
    - "pods/exec"
    - "namespaces"
    - "serviceaccounts"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: e2e
  labels:
    team: platform
subjects:
- kind: ServiceAccount
  name: default
  namespace: e2e-system
roleRef:
  kind: ClusterRole
  name: e2e
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: e2e-tests
  namespace: e2e-system
  labels:
    team: platform
spec:
  schedule: "* * * * 5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: e2e
            image: ghcr.io/maruina/kubecon-2024-eu:latest
            imagePullPolicy: IfNotPresent
            command:
            - /e2e-runner.sh
            - -test.v
            - -test.timeout=0
            - -fail-fast=true
            env:
              - name: ENV
                value: "dev"
              - name: DATADOG_API_KEY
                value: "PLACEHOLDER"
              - name: CLUSTER_NAME
                value: "kind"
          restartPolicy: Never
